Hospital/Models/ErrorViewModel.cs
using System;

namespace Hospital.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hospital/Models/Patient.cs
using Hospital.Validator;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class Patient
    {
        public int Id { get; set; }

        [Display(Name = "Full name")]
        [RegularExpression(@"^[a-zA-Z]([-']?[a-z]+)*( [a-zA-Z]([-']?[a-z]+)*)+$")]
        [Required]
        public string FullName { get; set; }

        [StringLength(60, MinimumLength = 5)]
        [Display(Name = "Place of residence")]
        public string PlaceOfResidence { get; set; }

        [DataType(DataType.Date)]
        [DateLessThanOrEqualToToday]
        [Display(Name = "Birthday")]
        public DateTime Birthday { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Receipt date")]
        [DateLessThanOrEqualToToday]
        public DateTime DateOfReceipt { get; set; }

        [Display(Name = "Doctors full name")]
        [RegularExpression(@"^[a-zA-Z]([-']?[a-z]+)*( [a-zA-Z]([-']?[a-z]+)*)+$")]
        [Required]
        public string DoctrosFullName { get; set; }

        [Display(Name = "Conclusion")]
        public string Colnclusion { get; set; }


    }
}

Hospital/Models/SearchPatientsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PagedList.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class SearchPatientsViewModel
    {
        public IPagedList pagedList { get; set; }
        public List<Patient> Patients { get; set; }
        public SelectList Types { get; set; }
        public Type Type { get; set; }

        public int PageSize { get; set; }

        public int PageNumber { get; set; }
        
    }
}

Hospital/Models/SearchTypes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Models
{
    public class SearchTypes
    {
        public static List<Type> GetTypes()
        {
            List<Type> result = new List<Type>();
            foreach (Type type in (Type[])Enum.GetValues(typeof(Type)))
            {
                result.Add(type);
            }
            return result;
        }
    }

    public enum Type
    {
        SURNAME_OR_ADDRESS,
        BIRTHDAY,
        FULL_DOCTORS_NAME_OR_RECEIPT_DATE
    }


}

Hospital/Controllers/HomeController.cs
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hospital/Controllers/HospitalController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class HospitalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hospital/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Hospital.Data;
using Hospital.Models;
using PagedList.Core;

namespace Hospital.Controllers
{
    public class PatientsController : Controller
    {
        private readonly HospitalContext _context;

        public PatientsController(HospitalContext context)
        {
            _context = context;
        }

        // GET: Patients
        public async Task<IActionResult> Index(int pageNumber = 1,int pageSize = 10)
        {
            SearchPatientsViewModel searchPatientsVM = new()
            {
                pagedList = _context.Patient.ToPagedList(pageNumber,pageSize),
                Patients = _context.Patient.ToPagedList(pageNumber, pageSize).ToList()
            };
            return View(searchPatientsVM);
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,PlaceOfResidence,Birthday,DateOfReceipt,DoctrosFullName,Colnclusion")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patient);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,PlaceOfResidence,Birthday,DateOfReceipt,DoctrosFullName,Colnclusion")] Patient patient)
        {
            if (id != patient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patient.FindAsync(id);
            _context.Patient.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patient.Any(e => e.Id == id);
        }
    }
}

Hospital/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Hospital/Views/Hospital/Index.cshtml
@model Hospital.Models.SearchPatientsViewModel

@{
    ViewData["Title"] = "Hospital database";
}

<link rel="stylesheet" href="~/css/cards.css" />

<input type='checkbox' class="invis" id='open_close' />
<input type='radio' name='opts' class="invis" id='opt1' />
<input type='radio' name='opts' class="invis" id='opt2' />
<input type='radio' name='opts' class="invis" id='opt3' />

<header class="header-base">
    <h1 class="header__title">CSS Only 'cause let's be clever or something?</h1>

    <p>
        Choose an Option
    </p>

    <div class="select-area">
        <label for="open_close" class="input-select">
            <!--  Make a Selection  –– label is generated by css content -->
        </label>

        <form asp-controller="Patients" asp-action="Index" method="get">
            <p>
                <input type="number" asp-for="PageSize" />
                <input type="number" asp-for="PageNumber" />
                <input type="submit" value="Filter" />
            </p>
        </form>
    </div>
</header>

<main role="main" class="main-content">

    <section class="options opt1">
        <div class="content">
            <h1>Option 1</h1>
            <p>
                You chose Option 1. That's super great.
            </p>
            <p>
                I hope this works out well for you.
            </p>
            <p>
                Strip steak short ribs swine ham hock, pork belly t-bone pork turducken filet mignon pancetta brisket jerky beef ribs tenderloin porchetta. Short ribs venison brisket doner, swine pancetta kielbasa turkey pig boudin spare ribs ham frankfurter. Rump kevin flank filet mignon short ribs tail pastrami meatloaf.
            </p>
            <p>
                Venison corned beef ham ribeye. Flank pig filet mignon tri-tip tenderloin ham tail salami spare ribs meatball tongue. Kielbasa strip steak pork belly jerky chuck tail capicola filet mignon meatloaf salami frankfurter boudin tongue ball tip corned beef.
            </p>
        </div>
    </section>


    <section class="options opt2">
        <div class="content">
            <h1>Option 2</h1>
            <p>
                You chose Option 2.
            </p>
            <p>
                Second best is alright I suppose.
            </p>
            <p>
                Strip steak short ribs swine ham hock, pork belly t-bone pork turducken filet mignon pancetta brisket jerky beef ribs tenderloin porchetta. Short ribs venison brisket doner, swine pancetta kielbasa turkey pig boudin spare ribs ham frankfurter. Rump kevin flank filet mignon short ribs tail pastrami meatloaf.
            </p>
            <p>
                Venison corned beef ham ribeye. Flank pig filet mignon tri-tip tenderloin ham tail salami spare ribs meatball tongue. Kielbasa strip steak pork belly jerky chuck tail capicola filet mignon meatloaf salami frankfurter boudin tongue ball tip corned beef.
            </p>
        </div>
    </section>


    <section class="options opt3">
        <div class="content">
            <h1>Option 3</h1>
            <p>
                You chose Option 3.
            </p>
            <p>
                This is probably the least desirable option.
                It's number 3 for a reason y'all.
            </p>
            <p>
                Strip steak short ribs swine ham hock, pork belly t-bone pork turducken filet mignon pancetta brisket jerky beef ribs tenderloin porchetta. Short ribs venison brisket doner, swine pancetta kielbasa turkey pig boudin spare ribs ham frankfurter. Rump kevin flank filet mignon short ribs tail pastrami meatloaf.
            </p>
            <p>
                Venison corned beef ham ribeye. Flank pig filet mignon tri-tip tenderloin ham tail salami spare ribs meatball tongue. Kielbasa strip steak pork belly jerky chuck tail capicola filet mignon meatloaf salami frankfurter boudin tongue ball tip corned beef.
            </p>
        </div>
    </section>

</main>

Hospital/Views/Patients/Create.cshtml
@model Hospital.Models.Patient

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfResidence" class="control-label"></label>
                <input asp-for="PlaceOfResidence" class="form-control" />
                <span asp-validation-for="PlaceOfResidence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfReceipt" class="control-label"></label>
                <input asp-for="DateOfReceipt" class="form-control" />
                <span asp-validation-for="DateOfReceipt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctrosFullName" class="control-label"></label>
                <input asp-for="DoctrosFullName" class="form-control" />
                <span asp-validation-for="DoctrosFullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colnclusion" class="control-label"></label>
                <input asp-for="Colnclusion" class="form-control" />
                <span asp-validation-for="Colnclusion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Patients/Delete.cshtml
@model Hospital.Models.Patient

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfResidence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfResidence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfReceipt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfReceipt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctrosFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctrosFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colnclusion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colnclusion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Hospital/Views/Patients/Details.cshtml
@model Hospital.Models.Patient

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlaceOfResidence)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlaceOfResidence)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Birthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfReceipt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfReceipt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoctrosFullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoctrosFullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Colnclusion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Colnclusion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Hospital/Views/Patients/Edit.cshtml
@model Hospital.Models.Patient

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaceOfResidence" class="control-label"></label>
                <input asp-for="PlaceOfResidence" class="form-control" />
                <span asp-validation-for="PlaceOfResidence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Birthday" class="control-label"></label>
                <input asp-for="Birthday" class="form-control" />
                <span asp-validation-for="Birthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfReceipt" class="control-label"></label>
                <input asp-for="DateOfReceipt" class="form-control" />
                <span asp-validation-for="DateOfReceipt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoctrosFullName" class="control-label"></label>
                <input asp-for="DoctrosFullName" class="form-control" />
                <span asp-validation-for="DoctrosFullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colnclusion" class="control-label"></label>
                <input asp-for="Colnclusion" class="form-control" />
                <span asp-validation-for="Colnclusion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Hospital/Views/Patients/Index.cshtml
@model Hospital.Models.SearchPatientsViewModel
@using PagedList.Core;
<link href="~/Content/PagedList.css" rel="stylesheet" type="pages/css" />

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<input type="number" asp-for="PageSize" id="PageSize" />
<input type="number" asp-for="PageNumber" id="PageNumber" />

<form asp-controller="Patients" asp-action="Index" method="get">
    <p>
        
        <input type="submit" value="Filter" />
    </p>
</form>

@using (Html.BeginForm("Index", "Patients", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("pageNumber", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].PlaceOfResidence)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].DateOfReceipt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].DoctrosFullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Patients[0].Colnclusion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Patients)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlaceOfResidence)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfReceipt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DoctrosFullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Colnclusion)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<br />
Page @(Model.PageNumber < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageNumber


<pager class="pager-container" list="Model.pagedList" asp-action="Index" asp-controller="Patients" />

Hospital/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hospital</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hospital</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Hospital - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>